exports = module.exports = [
  { winner: 'Kyle H', loser: 'Hunter', score: 17 },
  { winner: 'Kyle H', loser: 'Greg', score: 17 },
  { winner: 'Greg', loser: 'Alex', score: 19 },
  { winner: 'Kyle H', loser: 'Hunter', score: 19 },
  { winner: 'Alex', loser: 'Greg', score: 20 },
  { winner: 'Alex', loser: 'Mike', score: 21 },
  { winner: 'Kyle H', loser: 'Greg', score: 23 },
  { winner: 'Hunter', loser: 'Eli', score: 8 },
  { winner: 'Greg', loser: 'Hunter', score: 16 },
  { winner: 'Alex', loser: 'Kyle H', score: 16 },
  { winner: 'Greg', loser: 'Alex', score: 16 },
  { winner: 'Boris', loser: 'Alex', score: 18 },
  { winner: 'Vinnie', loser: 'Greg', score: 12 },
  { winner: 'Vinnie', loser: 'Hunter', score: 3 },
  { winner: 'Alex', loser: 'Eli', score: 13 },
  { winner: 'Kyle H', loser: 'Hunter', score: 23 },
  { winner: 'Kyle H', loser: 'Eli', score: 6 },
  { winner: 'Vinnie', loser: 'Alex', score: 19 },
  { winner: 'Greg', loser: 'Kyle H', score: 11 },
  { winner: 'Alex', loser: 'Greg', score: 20 },
  { winner: 'Greg', loser: 'Hunter', score: 25 },
  { winner: 'Alex', loser: 'Eli', score: 17 },
  { winner: 'Alex', loser: 'Hunter', score: 14 },
  { winner: 'Kyle B', loser: 'Diego', score: 13 },
  { winner: 'Greg', loser: 'Kyle B', score: 18 },
  { winner: 'Alex', loser: 'Diego', score: 18 },
  { winner: 'Mike', loser: 'Eli', score: 6 },
]